FROM python:3.12-slim

WORKDIR /app

COPY . /app

RUN pip install /app/dependency/v1/dependency
RUN mkdir -p /app/python-agent/glibc
RUN pip install --target /app/python-agent/glibc /app/dependency/v2/dependency
RUN mv /app/python-agent/glibc/dependency /app/python-agent/glibc/library_dependency
RUN pip install --target /app/python-agent/glibc /app/library
